# Docker compose used for production setup

name: watchers-prod

services:

# PostgreSQL database
  db:
    image: postgres:18-alpine
    container_name: poe-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data


# Backend API
  api:
    labels:
      - "com.centurylinklabs.watchtower.scope=prod"
    image: ghcr.io/mdahlmann/poetracker-api:latest
    container_name: poe-api
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ASPNETCORE_ENVIRONMENT=Production
      - OriginApiUrl=${ORIGIN_API_URL}
      - ActiveLeague=${ACTIVE_LEAGUE}
      - SyncInterval=30000
      - DiscordWebhook=${DISCORD_WEBHOOK}
      - UseMockData=false
    depends_on:
      - db
    networks:
      - default
      - watchers-net


# Frontend project
  client:
    labels:
      - "com.centurylinklabs.watchtower.scope=prod"
    image: ghcr.io/mdahlmann/poetracker-client:latest
    container_name: poe-client
    restart: always
    depends_on:
      - api
    networks:
      - default
      - watchers-net


# Fetches new images from GitHub Container Registry
# and replaces running containers with them.
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - DOCKER_API_VERSION=1.44
      - WATCHTOWER_SCOPE=prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    command: --interval 60 --cleanup

volumes:
  pgdata:

networks:
  watchers-net:
    external: true