# Docker compose used for local testing/hosting
# Only spins up a database container, API and Client runs through IDE

services:
  db:
    image: postgres:18-alpine
    container_name: poe-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data

volumes:
  pgdata_local:  