# Docker compose used for demo setup

services:

# PostgreSQL database
  db:
    image: postgres:18-alpine
    container_name: demo-poe-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data


# Backend API
  api:
    image: ghcr.io/mdahlmann/poetracker-api:latest
    container_name: demo-poe-api
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ASPNETCORE_ENVIRONMENT=Production
      - OriginApiUrl=${DEMO_ORIGIN_API_URL}
      - ActiveLeague=${DEMO_ACTIVE_LEAGUE}
      - SyncInterval=30000
      - DiscordWebhook=${DEMO_DISCORD_WEBHOOK}
      - UseMockData=true
    depends_on:
      - db
    networks:
      - default
      - watchers-net


# Frontend project
  client:
    image: ghcr.io/mdahlmann/poetracker-client:latest
    container_name: demo-poe-client
    restart: always
    depends_on:
      - api
    networks:
      - default
      - watchers-net

volumes:
  pgdata:
    name: demo_db_data

networks:
  watchers-net:
    external: true