// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PoeLeagueTracker.Infrastructure;

#nullable disable

namespace PoeLeagueTracker.Infrastructure.Migrations
{
    [DbContext(typeof(PoeTrackerDbContext))]
    [Migration("20260209214114_LeagueEntity")]
    partial class LeagueEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PoeLeagueTracker.Domain.Accounts.Account", b =>
                {
                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<int>("CompletedChallenges")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTwitchLinked")
                        .HasColumnType("boolean");

                    b.Property<string>("LeagueName")
                        .HasColumnType("text");

                    b.Property<string>("TwitchUsername")
                        .HasColumnType("text");

                    b.HasKey("AccountName");

                    b.HasIndex("LeagueName");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Characters.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<int>("ClassName")
                        .HasColumnType("integer");

                    b.Property<bool>("Dead")
                        .HasColumnType("boolean");

                    b.Property<int?>("Depth")
                        .HasColumnType("integer");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<bool>("Retired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccountName");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Leagues.League", b =>
                {
                    b.Property<string>("LeagueName")
                        .HasColumnType("text");

                    b.HasKey("LeagueName");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Accounts.Account", b =>
                {
                    b.HasOne("PoeLeagueTracker.Domain.Leagues.League", null)
                        .WithMany("Accounts")
                        .HasForeignKey("LeagueName");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Characters.Character", b =>
                {
                    b.HasOne("PoeLeagueTracker.Domain.Accounts.Account", null)
                        .WithMany("Characters")
                        .HasForeignKey("AccountName");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Leagues.League", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
