// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PoeLeagueTracker.Infrastructure;

#nullable disable

namespace PoeLeagueTracker.Infrastructure.Migrations
{
    [DbContext(typeof(PoeTrackerDbContext))]
    [Migration("20260503195507_AddUserEntity")]
    partial class AddUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PoeLeagueTracker.Domain.Accounts.Account", b =>
                {
                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.HasKey("AccountName");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Characters.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Challenges")
                        .HasColumnType("integer");

                    b.Property<int>("ClassName")
                        .HasColumnType("integer");

                    b.Property<bool>("Dead")
                        .HasColumnType("boolean");

                    b.Property<int?>("Depth")
                        .HasColumnType("integer");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<bool>("Retired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccountName");

                    b.HasIndex("LeagueName");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Leagues.League", b =>
                {
                    b.Property<string>("LeagueName")
                        .HasColumnType("text");

                    b.HasKey("LeagueName");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Characters.Character", b =>
                {
                    b.HasOne("PoeLeagueTracker.Domain.Accounts.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoeLeagueTracker.Domain.Leagues.League", "League")
                        .WithMany("Characters")
                        .HasForeignKey("LeagueName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("League");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Users.User", b =>
                {
                    b.OwnsOne("PoeLeagueTracker.Domain.Users.PasswordHash", "HashedPassword", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("HashedPassword")
                        .IsRequired();
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("PoeLeagueTracker.Domain.Leagues.League", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
